spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${cola.rocketmq.url}
rocketmq:
  name-server: ${cola.rocketmq.url}
  broker:
    check: false # ???????????RocketMQ?????SpringCloud Stream???MQ??????????RocketMQ?????????????????MQ Client???????RocketMQ????????????????RocketMQ?????
  # ???????RocketMQ????????????????????????false