# ???????????????????????????????????????????
cola:
  nacos:
    server:
      url: 127.0.0.1:8848 # cola.nacos.server.url - Nacos ???+??? #??????????????
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/nfturbo # cola.mysql.url - MySQL ???+????? #??????????????
    username: root # cola.mysql.username - MySQL ???? #??????????????
    password: wangjin521 # cola.mysql.password - MySQL ??? #??????????????
  redis:
    url: 127.0.0.1  # cola.redis.url - Redis ??? #??????????????
    port: 6379  # cola.redis.port - Redis ???? #??????????????
    password:  # cola.redis.password - Redis ??? #??????????????
  elasticsearch:
    enable: false # cola.elasticsearch.enable #??????es(??????mock)???????true
    url: 127.0.0.1:9200 # cola.elasticsearch.url - ElasticSearch ???+??? ##??????es(??????mock)???????true
    username: elastic # cola.elasticsearch.username - ElasticSearch ???? ##??????es(??????mock)???????true
    password: 123456  # cola.elasticsearch.password - ElasticSearch ??? ##??????es(??????mock)???????true
  xxl-job:
    url: 127.0.0.1:4060  # cola.xxl-job.url - XXL-JOB ??? # ?????????????????
    appName: xxl-job-executor  # cola.xxl-job.appName - ?????xxl-job????????????????????????
    accessToken: default_token # cola.xxl-job.accessToken - ?????xxl-job????token???????????????
  sentinel:
    url: 127.0.0.1:8099 # cola.sentinel.url - Sentinel ???+??? # ????sentinel ??????????sentinel??????
    port: 8098 # cola.sentinel.port - Sentinel ??? # ????sentinel ??????????sentinel????
    nacos:
      data-id: cola-gateway-sentinel # cola.sentinel.nacos.data-id - Sentinel????? nacos ? data-id # ????sentinel ?????????? ?nacos????data-id
  rocketmq:
    url: 127.0.0.1:9876 # cola.rocketmq.url - RocketMQ ???+??? # ?????RocketMQ???????????
  dubbo:
    nacos:
      namespace: 9fdee59e-949c-441a-9545-b72d92357ae4  # cola.dubbo.nacos.namespace - ???nacos??????dubbo??namespce????????????????????????? #??????????????
      group: dubbo  # cola.dubbo.nacos.group - ???nacos??????dubbo?? group????????????????????????? #??????????????
  seata:
    nacos:
      data-id: seataServer.properties # cola.seata.nacos.data-id - Seata ???Nacos ????? data-id #??????????????
      group: seata # cola.seata.nacos.group - Seata ???Nacos ????? data-id #??????????????
      namespace: 7ebdfb9b-cd9d-4a5e-8969-1ada0bb9ba04 # cola.seata.nacos.namespace - Seata ???Nacos ????? namespace #??????????????