server:
  port: 8082

spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml


#dubbo:
#  protocol:
#    name: dubbo
#    host: 127.0.0.1
#    port: 20880
#  application:
#    qos-port: 33333
